"""H5netcdf-backed dataset serializer (plan Section 4.6).

Concrete adapter for ``storage.interfaces.DatasetSerializer``. Owns the
h5netcdf dependency; domain contracts (``contracts/datasets.py``) never
import this module. Writes a deterministic logical schema (fixed dtypes,
no wall-clock history attribute); round trips are compared for logical
equality, not byte-for-byte identity across platforms.
"""

from __future__ import annotations

import io

import xarray as xr


class H5NetcdfDatasetSerializer:
    """Implements storage.interfaces.DatasetSerializer using h5netcdf."""

    def serialize(self, dataset: xr.Dataset) -> bytes:
        buffer = io.BytesIO()
        # xarray's to_netcdf never writes a wall-clock "history" attribute
        # unless the caller adds one; we deliberately do not add one, so
        # regenerated bytes only vary with dataset content.
        dataset.to_netcdf(buffer, engine="h5netcdf", format="NETCDF4")
        return buffer.getvalue()

    def deserialize(self, payload: bytes) -> xr.Dataset:
        buffer = io.BytesIO(payload)
        with xr.open_dataset(buffer, engine="h5netcdf") as opened:
            return opened.load()
