"""Self-contained, deterministic two-page forecast PDF; no network, storage or AI."""

from __future__ import annotations

import re
from datetime import datetime
from io import BytesIO
from typing import Any
from xml.sax.saxutils import escape
from zoneinfo import ZoneInfo

from reportlab.lib.colors import HexColor
from reportlab.lib.styles import ParagraphStyle
from reportlab.pdfgen.canvas import Canvas
from reportlab.platypus import Paragraph

from mesoforge.presentation.forecast_document import DOCUMENT_POLICY

_INK = "#152D3A"
_MUTED = "#506874"
_TEAL = "#007F82"
_AMBER = "#D87924"
_BLUE = "#407EBA"
_PALE = "#EDF4F5"
_LINE = "#D2DFE4"
_WIDTH, _HEIGHT, _MARGIN = 612, 792, 40
_COMPASS = (
    "N",
    "NNE",
    "NE",
    "ENE",
    "E",
    "ESE",
    "SE",
    "SSE",
    "S",
    "SSW",
    "SW",
    "WSW",
    "W",
    "WNW",
    "NW",
    "NNW",
)


def _f(kelvin: float) -> float:
    return (kelvin - 273.15) * 1.8 + 32


def _value(value: float | None, *, digits: int = 0, unit: str = "") -> str:
    return "Unavailable" if value is None else f"{value:.{digits}f}{unit}"


def _amount(value: float | None) -> str:
    if value is None:
        return "Unavailable"
    inches = value / 25.4
    # Do not render a positive small amount as a dry zero through rounding.
    if 0 < inches < 0.005:
        return "<0.01 in"
    return f"{inches:.2f} in"


def _safe_label(value: Any, fallback: str = "unavailable") -> str:
    return (
        value
        if isinstance(value, str) and re.fullmatch(r"[A-Za-z0-9_.:-]{1,80}", value)
        else fallback
    )


def _text(
    canvas: Canvas,
    text: str,
    x: float,
    top: float,
    width: float,
    *,
    size: float = 9,
    color: str = _INK,
    bold: bool = False,
    max_height: float = 80,
    draw: bool = True,
) -> float:
    style = ParagraphStyle(
        "forecast",
        fontName="Helvetica-Bold" if bold else "Helvetica",
        fontSize=size,
        leading=size * 1.32,
        textColor=HexColor(color),
        spaceAfter=0,
    )
    paragraph = Paragraph(escape(text), style)
    _, height = paragraph.wrap(width, max_height)
    if height > max_height:
        raise ValueError("Forecast text exceeds its designed PDF box; refuse clipped output")
    if draw:
        paragraph.drawOn(canvas, x, _HEIGHT - top - height)
    return float(height)


def _line(canvas: Canvas, x: float, top: float, width: float) -> None:
    canvas.setStrokeColor(HexColor(_LINE))
    canvas.setLineWidth(0.6)
    canvas.line(x, _HEIGHT - top, x + width, _HEIGHT - top)


def _header(canvas: Canvas, document: dict[str, Any], page: int) -> None:
    canvas.setFillColor(HexColor(_INK))
    canvas.rect(0, _HEIGHT - 75, _WIDTH, 75, fill=1, stroke=0)
    _text(canvas, "MESO", _MARGIN, 24, 74, size=19, color="#FFFFFF", bold=True)
    _text(canvas, "FORGE", 108, 24, 100, size=19, color="#79D6CF", bold=True)
    _text(canvas, "LOCAL WEATHER. INFORMED DECISIONS.", 305, 34, 265, size=8.2, color="#BBD4DC")
    if document["fixture"]:
        canvas.setFillColor(HexColor("#FFF1C9"))
        canvas.rect(0, _HEIGHT - 96, _WIDTH, 21, fill=1, stroke=0)
        _text(
            canvas,
            "TEST FIXTURE - DESIGN DEMONSTRATION, NOT A REAL FORECAST",
            _MARGIN,
            80,
            540,
            size=8,
            bold=True,
        )
    _line(canvas, _MARGIN, 735, _WIDTH - 2 * _MARGIN)
    zone = ZoneInfo(document["display_timezone"])
    issued = datetime.fromisoformat(document["issued_at"]).astimezone(zone)
    end = datetime.fromisoformat(document["valid_end"]).astimezone(zone)
    _text(
        canvas,
        f"Generated by MesoForge | Issued {issued:%b %d, %Y %I:%M %p %Z}",
        _MARGIN,
        744,
        510,
        size=7.3,
        color=_MUTED,
    )
    revision = document["revision"]
    revision = revision[:8] if re.fullmatch(r"[0-9a-f]{40}", str(revision)) else "unavailable"
    provider, model = (_safe_label(document["ai"].get(key)) for key in ("provider", "model"))
    _text(
        canvas,
        f"Valid through {end:%b %d %I:%M %p %Z} | AI: {provider}/{model} | Rev {revision}",
        _MARGIN,
        758,
        510,
        size=6.8,
        color=_MUTED,
    )
    _text(canvas, str(page) + " / 2", 540, 753, 32, size=8, color=_MUTED)


def _wind(day: dict[str, Any]) -> str:
    speed, direction = day["vector_mean_wind_speed_mps"], day["vector_mean_wind_direction"]
    if speed is None:
        return "Unavailable"
    if direction is None:
        return "Calm vector mean"
    compass = _COMPASS[int((direction + 11.25) // 22.5) % 16]
    return f"{compass} {speed / 0.44704:.0f} mph"


def _outlook(canvas: Canvas, document: dict[str, Any]) -> None:
    _header(canvas, document, 1)
    location = document["location"]
    name = str(location["name"])
    _text(canvas, "5-Day Forecast", _MARGIN, 111, 530, size=28, bold=True)
    # State is not inferred from arbitrary coordinates or embedded in science.
    _text(canvas, name, _MARGIN, 152, 530, size=17, bold=True, max_height=24)
    _text(
        canvas,
        f"{location['lat']:.5f}, {location['lon']:.5f} | {document['display_timezone']}",
        _MARGIN,
        178,
        530,
        size=9,
        color=_MUTED,
    )
    zone = ZoneInfo(document["display_timezone"])
    start = datetime.fromisoformat(document["valid_start"]).astimezone(zone)
    end = datetime.fromisoformat(document["valid_end"]).astimezone(zone)
    last_day = datetime.fromisoformat(document["days"][-1]["date"])
    _text(
        canvas,
        f"{start:%A, %B %d} - {last_day:%A, %B %d, %Y}",
        _MARGIN,
        199,
        530,
        size=10,
        color=_MUTED,
    )
    _text(canvas, document["headline"], _MARGIN, 231, 532, size=17, bold=True, max_height=46)
    gap, width, top, height = 8, 100, 294, 219
    for index, day in enumerate(document["days"]):
        x = _MARGIN + index * (width + gap)
        canvas.setFillColor(HexColor(_PALE))
        canvas.roundRect(x, _HEIGHT - top - height, width, height, 6, fill=1, stroke=0)
        date = datetime.fromisoformat(day["date"])
        _text(
            canvas,
            date.strftime("%a").upper(),
            x + 10,
            top + 11,
            80,
            size=10,
            color=_TEAL,
            bold=True,
        )
        _text(canvas, date.strftime("%b %d"), x + 10, top + 27, 80, size=9, color=_MUTED)
        high = _value(_f(day["high_k"]) if day["high_k"] is not None else None, unit="°")
        low = _value(_f(day["low_k"]) if day["low_k"] is not None else None, unit="°")
        temps = (
            high + " / " + low
            if day["high_k"] is not None and day["low_k"] is not None
            else "Unavailable"
        )
        _text(
            canvas,
            temps,
            x + 10,
            top + 47,
            82,
            size=17 if temps != "Unavailable" else 10,
            bold=True,
        )
        _text(canvas, "Hourly high / low °F", x + 10, top + 73, 82, size=6.8, color=_MUTED)
        _text(canvas, "Most frequent outlook", x + 10, top + 88, 82, size=6.4, color=_MUTED)
        _text(
            canvas,
            day["most_frequent_hourly_condition"],
            x + 10,
            top + 102,
            82,
            size=8,
            max_height=32,
        )
        chance = day["maximum_hourly_pop"]
        _text(canvas, "Max hourly PoP", x + 10, top + 138, 82, size=7, color=_MUTED)
        _text(
            canvas,
            _value(chance * 100 if chance is not None else None, unit="%"),
            x + 10,
            top + 150,
            82,
            size=10,
            bold=True,
        )
        _text(canvas, "Liquid: " + _amount(day["qpf_kg_m2"]), x + 10, top + 168, 82, size=8)
        _text(canvas, _wind(day), x + 10, top + 184, 82, size=8)
        gust = day["max_gust_mps"]
        _text(
            canvas,
            "Gust: " + _value(gust / 0.44704 if gust is not None else None, unit=" mph"),
            x + 10,
            top + 199,
            82,
            size=8,
        )
    _text(canvas, "OUTLOOK NOTES", _MARGIN, 535, 532, size=9, color=_TEAL, bold=True)
    transitions = document["transitions"]
    if transitions:
        note_top = 555.0
        rendered = 0
        for item in transitions[:3]:
            note_height = _text(
                canvas, item + ".", _MARGIN, note_top, 532, size=9, max_height=80, draw=False
            )
            if note_top + note_height > 627:
                break
            _text(canvas, item + ".", _MARGIN, note_top, 532, size=9, max_height=72)
            note_top += note_height + 5
            rendered += 1
        if len(transitions) > rendered:
            _text(
                canvas,
                "Some transition notes omitted for space; hourly numerical timelines follow.",
                _MARGIN,
                note_top,
                532,
                size=8,
                color=_MUTED,
                max_height=16,
            )
    else:
        _text(
            canvas,
            "No supported major transition was identified in the saved hourly forecast.",
            _MARGIN,
            555,
            532,
            size=9,
        )
    missing = any(
        metric["available_hours"] != metric["expected_hours"]
        for day in document["days"]
        for metric in day["availability"].values()
    )
    note = (
        "Some daily fields are unavailable because their hourly guidance is incomplete. "
        if missing
        else ""
    )
    note += "PoP is the highest hourly chance, not the probability for the whole day. "
    note += "Liquid totals preserve small amounts. Forecasts can change as new guidance arrives."
    _text(canvas, note, _MARGIN, 653, 532, size=8, color=_MUTED, max_height=38)
    _text(
        canvas,
        "AI desk: " + document["ai"]["display_status"],
        _MARGIN,
        704,
        532,
        size=8,
        color=_MUTED,
        max_height=21,
    )
    # Explicit valid period remains present even when the end is next day's midnight.
    canvas.setSubject(f"Forecast intervals ({start.isoformat()}, {end.isoformat()}]")
    canvas.showPage()


def _chart(
    canvas: Canvas,
    document: dict[str, Any],
    top: float,
    title: str,
    series: list[tuple[str, list[float | None], str]],
    *,
    unit: str,
    fixed_range: tuple[float, float] | None = None,
    bars: bool = False,
) -> None:
    left, width, height = 68.0, 495.0, 62.0
    _text(canvas, title, _MARGIN, top, 530, size=12, bold=True)
    plot_top = top + 32
    all_values = [value for _, values, _ in series for value in values if value is not None]
    if fixed_range:
        low, high = fixed_range
    elif all_values:
        low, high = min(all_values), max(all_values)
        span = max(high - low, 1)
        low, high = low - span * 0.12, high + span * 0.12
        if bars:
            low, high = 0, max(max(all_values) * 1.12, 0.01)
        elif unit == "mph":
            low, high = 0, max(high, 1)
    else:
        low, high = 0, 1
    rows = document["hours"]
    count = len(rows)
    for part in range(3):
        y = plot_top + height * part / 2
        _line(canvas, left, y, width)
        amount = high - (high - low) * part / 2
        label = f"{amount:.2f}" if unit == "in" else f"{amount:.0f}"
        _text(canvas, label, 40, y - 5, 25, size=7, color=_MUTED)
    legend_x = left
    for label, values, color in series:
        _text(canvas, label + " (" + unit + ")", legend_x, top + 17, 190, size=7.5, color=color)
        legend_x += 155
        canvas.setStrokeColor(HexColor(color))
        canvas.setFillColor(HexColor(color))
        canvas.setLineWidth(1.7)
        previous: tuple[float, float] | None = None
        for i, value in enumerate(values):
            if value is None:
                previous = None
                continue
            x = left + width * (i + 0.5) / count
            y = _HEIGHT - plot_top - height + height * (value - low) / (high - low)
            if bars:
                bottom = _HEIGHT - plot_top - height
                canvas.rect(
                    x - width / count * 0.35,
                    bottom,
                    width / count * 0.7,
                    max(0, y - bottom),
                    stroke=0,
                    fill=1,
                )
            elif previous:
                canvas.line(*previous, x, y)
            else:
                canvas.circle(x, y, 1.2, fill=1, stroke=0)
            previous = (x, y)
    if not all_values:
        _text(canvas, "Guidance unavailable", left + 170, plot_top + 29, 200, size=10, color=_MUTED)
    elapsed = 0
    for day in document["days"]:
        middle = left + width * (elapsed + day["hours"] / 2) / count
        date = datetime.fromisoformat(day["date"])
        _text(
            canvas,
            date.strftime("%a %d"),
            middle - 23,
            plot_top + height + 6,
            54,
            size=7.2,
            color=_MUTED,
        )
        elapsed += day["hours"]


def _detail(canvas: Canvas, document: dict[str, Any]) -> None:
    _header(canvas, document, 2)
    _text(canvas, "The forecast, hour by hour", _MARGIN, 111, 532, size=24, bold=True)
    _text(
        canvas,
        "Continuous hourly timelines include all overnight periods. "
        "Gaps mean unavailable guidance.",
        _MARGIN,
        147,
        532,
        size=8.2,
        color=_MUTED,
    )
    hours = document["hours"]
    temperature = [
        _f(row["temperature"]) if row["temperature"] is not None else None for row in hours
    ]
    dewpoint = [_f(row["dew_point"]) if row["dew_point"] is not None else None for row in hours]
    _chart(
        canvas,
        document,
        169,
        "Temperature & moisture",
        [("Temperature", temperature, _AMBER), ("Dew point", dewpoint, _TEAL)],
        unit="°F",
    )
    _chart(
        canvas,
        document,
        286,
        "Precipitation timing",
        [
            (
                "Hourly PoP",
                [row["pop"] * 100 if row["pop"] is not None else None for row in hours],
                _BLUE,
            )
        ],
        unit="%",
        fixed_range=(0, 100),
    )
    # A second small amount strip uses its own axis; never rescale QPF into probability.
    qpf = [row["qpf"] / 25.4 if row["qpf"] is not None else None for row in hours]
    _chart(
        canvas,
        document,
        403,
        "Liquid precipitation amount",
        [("Hourly liquid", qpf, _TEAL)],
        unit="in",
        bars=True,
    )
    wind = [row["wind_speed"] / 0.44704 if row["wind_speed"] is not None else None for row in hours]
    gusts = [row["wind_gust"] / 0.44704 if row["wind_gust"] is not None else None for row in hours]
    _chart(
        canvas,
        document,
        520,
        "Wind & gusts",
        [("Sustained", wind, _TEAL), ("Gust", gusts, _AMBER)],
        unit="mph",
    )
    _text(canvas, "SKY COVER", _MARGIN, 642, 532, size=9, color=_TEAL, bold=True)
    for i, day in enumerate(document["days"]):
        x = _MARGIN + i * 108
        _text(
            canvas,
            datetime.fromisoformat(day["date"]).strftime("%a %d"),
            x,
            660,
            100,
            size=8,
            color=_MUTED,
        )
        subset = [
            row
            for row in hours
            if datetime.fromisoformat(day["start"])
            < datetime.fromisoformat(row["valid_time"])
            <= datetime.fromisoformat(day["end"])
        ]
        shades = {
            "clear": "#E8F4F5",
            "mostly_clear": "#BBDADC",
            "partly_cloudy": "#8AAEB8",
            "mostly_cloudy": "#527580",
            "cloudy": "#223F4F",
            None: "#FFFFFF",
        }
        for j, hour in enumerate(subset):
            canvas.setFillColor(HexColor(shades.get(hour["sky"], "#FFFFFF")))
            canvas.rect(
                x + 100 * j / len(subset), _HEIGHT - 684, 100 / len(subset), 12, fill=1, stroke=0
            )
    _text(
        canvas,
        "Sky timeline: pale = clearer, dark = cloudier, white = unavailable. "
        "Each strip runs midnight to midnight.",
        _MARGIN,
        692,
        532,
        size=7.3,
        color=_MUTED,
    )
    _text(
        canvas,
        "Hourly chance refers to more than 0.01 in liquid. "
        "Wind uses vector means; gusts are maxima.",
        _MARGIN,
        709,
        532,
        size=7.3,
        color=_MUTED,
    )
    canvas.showPage()


def render_forecast_pdf(document: dict[str, Any]) -> bytes:
    """Render a verified product summary without retaining secrets or internal paths."""
    if document.get("document_policy") != DOCUMENT_POLICY or len(document.get("days", [])) != 5:
        raise ValueError("A validated five-day forecast document is required")
    for day in document["days"]:
        if day["hours"] not in (23, 24, 25):
            raise ValueError("Only complete local calendar days can be rendered")
    if len(document["hours"]) != sum(day["hours"] for day in document["days"]):
        raise ValueError("Daily and hourly PDF coverage differs")
    name = document["location"]["name"]
    if not isinstance(name, str) or len(name) > 80 or any(ord(char) < 32 for char in name):
        raise ValueError("Invalid display name")
    stream = BytesIO()
    canvas = Canvas(stream, pagesize=(_WIDTH, _HEIGHT), invariant=1, pageCompression=1)
    canvas.setTitle("MesoForge 5-Day Forecast - " + name)
    canvas.setAuthor("MesoForge")
    canvas.setCreator("MesoForge deterministic forecast presentation")
    _outlook(canvas, document)
    _detail(canvas, document)
    canvas.save()
    return stream.getvalue()
